[project]
name = "vulnerability_management"
version = "0.1.0"
description = "vulnerability-management using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.175.0,<1.0.0"
]

[project.scripts]
vulnerability_management = "vulnerability_management.main:run"
run_crew = "vulnerability_management.main:run"
train = "vulnerability_management.main:train"
replay = "vulnerability_management.main:replay"
test = "vulnerability_management.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
