vulnerability_discovery_task:
  description: >
    Perform comprehensive vulnerability scanning on the target systems specified in {target_systems}.
    Use appropriate scanning techniques and tools to identify potential security weaknesses.
    Focus on network services, web applications, operating systems, and known CVE vulnerabilities.
    Ensure scanning is thorough but non-disruptive to production systems.
  expected_output: >
    A detailed vulnerability scan report containing:
    - List of discovered vulnerabilities with CVE IDs where applicable
    - Affected systems and services
    - Technical details of each vulnerability
    - Initial severity assessment
    - Scan methodology and tools used
  agent: vulnerability_scanner

vulnerability_analysis_task:
  description: >
    Analyze the discovered vulnerabilities from the scanning results.
    Provide detailed technical analysis of each vulnerability including:
    - Root cause analysis
    - Attack vectors and exploitation methods
    - Technical impact assessment
    - Evidence and proof of concept where appropriate
    Review current security controls and their effectiveness against identified vulnerabilities.
  expected_output: >
    A comprehensive vulnerability analysis report containing:
    - Detailed technical analysis for each vulnerability
    - Exploitation scenarios and attack vectors
    - Current security control effectiveness
    - Technical recommendations for each finding
  agent: vulnerability_analyst

risk_prioritization_task:
  description: >
    Evaluate and prioritize the analyzed vulnerabilities based on:
    - Business impact and criticality of affected systems
    - Likelihood of exploitation in current threat landscape
    - CVSS scores and industry threat intelligence
    - Organizational risk tolerance and compliance requirements
    Create a risk-based prioritization matrix for remediation efforts.
  expected_output: >
    A risk assessment and prioritization report containing:
    - Risk matrix with high, medium, and low priority vulnerabilities
    - Business impact assessment for each vulnerability
    - Threat landscape analysis and exploitation likelihood
    - Recommended remediation timeline based on risk levels
  agent: risk_assessor

remediation_planning_task:
  description: >
    Develop comprehensive remediation plans for the prioritized vulnerabilities.
    Create actionable recommendations that include:
    - Specific patches and updates required
    - Configuration changes and security hardening measures
    - Compensating controls for vulnerabilities that cannot be immediately patched
    - Implementation timeline and resource requirements
    - Testing and validation procedures
  expected_output: >
    A detailed remediation plan document containing:
    - Step-by-step remediation procedures for each vulnerability
    - Patch management recommendations and deployment strategies
    - Security configuration guidelines and hardening measures
    - Compensating controls and temporary mitigation strategies
    - Implementation timeline with milestones and resource allocation
    - Testing and validation procedures to ensure successful remediation
  agent: remediation_advisor
  output_file: vulnerability_remediation_plan.md
